name: Publish
on:
  push:
    branches:
    - main

jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
        architecture: x64

    - name: Install requirements
      run: python3 -m pip install -r lock.txt

    - name: Deploy 🚀
      run: python3 -m mkdocs gh-deploy --force
